version: '3'
services:
    manager-nginx:
        build:
            context: ./manager/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./manager:/app
            - ./manager/docker/development/certbot/conf:/etc/letsencrypt
            - ./manager/docker/development/certbot/www:/var/www/certbot
        depends_on:
            - manager-php-fpm
        ports:
            - "80:80"
            - "443:443"
    manager-php-fpm:
        build:
            context: ./manager/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./manager:/app
        depends_on:
            - manager-postgres
            - mailer
    manager-php-cli:
        build:
            context: ./manager/docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./manager:/app
            - composer:/root/.composer/cache
        depends_on:
            - manager-postgres
            - mailer
    manager-node:
        image: node:14.16.0-alpine
        volumes:
            - ./manager:/app
        working_dir: /app
    manager-postgres:
        image: postgres:13.1-alpine
        volumes:
            - manager-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "5432:5432"
    mailer:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
    certbot:
        image: certbot/certbot
        volumes:
            - ./manager/docker/development/certbot/conf:/etc/letsencrypt
            - ./manager/docker/development/certbot/www:/var/www/certbot
volumes:
    manager-postgres:
    composer:
